export const IPA_SAFETY_NOTE =
  "IPA mapping is approximate deterministic inspection metadata only; no audio validation or pronunciation correctness claim is made.";

export const DEVANAGARI_IPA_MAP = {
  "अ": "ə",
  "आ": "aː",
  "इ": "i",
  "ई": "iː",
  "उ": "u",
  "ऊ": "uː",
  "ऋ": "r̩",
  "ए": "eː",
  "ऐ": "ai",
  "ओ": "oː",
  "औ": "au",
  "क": "k",
  "ख": "kʰ",
  "ग": "ɡ",
  "घ": "ɡʱ",
  "ङ": "ŋ",
  "च": "t͡ɕ",
  "छ": "t͡ɕʰ",
  "ज": "d͡ʑ",
  "झ": "d͡ʑʱ",
  "ञ": "ɲ",
  "ट": "ʈ",
  "ठ": "ʈʰ",
  "ड": "ɖ",
  "ढ": "ɖʱ",
  "ण": "ɳ",
  "त": "t̪",
  "थ": "t̪ʰ",
  "द": "d̪",
  "ध": "d̪ʱ",
  "न": "n̪",
  "प": "p",
  "फ": "pʰ",
  "ब": "b",
  "भ": "bʱ",
  "म": "m",
  "य": "j",
  "र": "r",
  "ल": "l",
  "व": "ʋ",
  "श": "ɕ",
  "ष": "ʂ",
  "स": "s̪",
  "ह": "ɦ",
  "ं": "̃",
  "ः": "ɦ",
  "्": "",
};
