"""
routers/export.py
PDF export for validated Sanskrit verses.

POST /api/v3/export/pdf
  Body: {"verse": "...", "pattern": "...", "title": "..."}
  Returns: application/pdf
"""

from __future__ import annotations

import io
from typing import Optional

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import Response
from pydantic import BaseModel, Field

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas


router = APIRouter(prefix="/api/v3/export", tags=["Export"])


class ExportRequest(BaseModel):
    verse: str = Field(..., min_length=1, max_length=5000)
    pattern: Optional[str] = Field(None, max_length=500)
    title: Optional[str] = Field(None, max_length=200)


def _render_pdf(req: ExportRequest) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Title
    y = height - 3 * cm
    if req.title:
        c.setFont("Helvetica-Bold", 18)
        c.drawCentredString(width / 2, y, req.title)
        y -= 1.5 * cm

    # Sanskrit verse (one line per pāda)
    c.setFont("Helvetica", 16)
    lines = [ln for ln in req.verse.splitlines() if ln.strip()]
    for line in lines:
        c.drawCentredString(width / 2, y, line)
        y -= 1.0 * cm

    # Scansion pattern
    if req.pattern:
        y -= 1.0 * cm
        c.setFont("Courier", 12)
        c.drawCentredString(width / 2, y, req.pattern)

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width / 2, 2 * cm, "Generated by Aigaane · aigaane.in")

    c.showPage()
    c.save()
    return buffer.getvalue()


@router.post(
    "/pdf",
    status_code=status.HTTP_200_OK,
    summary="Export a verse as PDF",
)
def export_pdf(payload: ExportRequest) -> Response:
    try:
        pdf_bytes = _render_pdf(payload)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF generation failed: {e}",
        )
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": 'attachment; filename="aigaane-verse.pdf"',
        },
    )


if __name__ == "__main__":
    # Self-test: generate a small PDF
    req = ExportRequest(
        title="Test Verse",
        verse="sarasvatī namastubhyaṃ\nvarade kāmarūpiṇī\nvidyārambhaṃ kariṣyāmi\nsiddhiḥ bhavatu me sadā",
        pattern="LGLGLGGG LLGGLGLG GGGGLGGL GGLLLGLG",
    )
    pdf = _render_pdf(req)
    assert pdf.startswith(b"%PDF"), "Not a valid PDF"
    assert len(pdf) > 1000, "PDF too small"
    print(f"export.py OK — {len(pdf)} bytes")